package aigc.gameflow.image;

public enum GenerationEventType {
    TASK_CREATED,
    TASK_QUEUED,
    TASK_RUNNING,
    TASK_CANCELED,
    TASK_RETRY_REQUESTED,
    TASK_RETRY_SCHEDULED,
    TASK_LEASE_EXPIRED,
    TASK_RESULT_IGNORED,
    TASK_DEAD_LETTERED,
    PROVIDER_SELECTED,
    PROVIDER_REQUEST_SENT,
    IMAGE_STORED,
    CALLBACK_SENT,
    CALLBACK_FAILED,
    TASK_SUCCESS,
    TASK_FAILED
}
